### ISSUE TITLE
Erro ao acessar "Meu perfil"

### ISSUE THREAD

**Issue by thaisrigolon** [culturagovbr/mapasculturais-bibliotecas#25]
Verificar erro ao acessar o perfil das bibliotecas, via "Meu perfil". A página quebra em produção.

**Comment by marcus2703** [comment]
Teste o acesso ao link "Meu Perfil" e o mesmo abriu de forma correta, sem quebrar nenhum css.

**Comment by marcus2703** [comment]
Atualizado em 31/07. Sem problemas em produção.
